{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "fc836849_8e210de4",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1004034
      },
      "writtenOn": "2023-11-14T14:41:37Z",
      "side": 1,
      "message": "Please mention in the commit message under which circumstances did you hit this error ?",
      "revId": "880408649cbfe26fc647f6d495333cbe40a02585",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    }
  ]
}